site_name: Areto Documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - API Reference:
    - Overview: api_reference/overview.md
    - Student:  api_reference/student.md
    - Course:  api_reference/course.md
    - Section: api_reference/section.md
    - Pool:  api_reference/pool.md
    - Group:  api_reference/group.md

extra_css:
  - overrides/custom.css